extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-R
  container: r-base
pipelines:
  pullRequest:
    setup:
      steps:
      - groovy: checkout scm
    build:
      steps:
      - sh: R CMD check .
        name: R-check
      - sh: R CMD build .
        name: R-build
      - sh: Rscript -e "devtools::test()"
        name: "R execute unit tests from testthat"
  release:
    setup:
      steps:
      - groovy: git 'https://REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME.git'
        when: "prow"
      - groovy: checkout scm
        when: "!prow"
      - sh: git checkout master
        name: git-checkout-master
        comment: ensure we're not on a detached head
        when: "!prow"
      - sh: git config --global credential.helper store
        when: "!prow"
        name: git-config
#      - sh: jx step git credentials
      - sh: echo "jx step git credentials - missing TODO"
        when: "!prow"
        name: git-credentials
    setVersion:
      steps:
      - sh: echo "0.0.3 TODO "> VERSION
        name: next-version
        comment: so we can retrieve the version in later steps
      # TODO set the version in source?
      - sh: echo " TODO tag version""
        name: tag-version
    build:
      steps:
      - sh: R CMD check .
        name: R-check
      - sh: R CMD build .
        name: R-build
      - sh: R CMD INSTALL .
        name: R-install
      - sh: Rscript -e "devtools::test()"
        name: "R execute unit tests from testthat"